import { StyleSheet } from "react-native-unistyles";
import { Colors } from "@/shared/constants/color";

export const createDonationScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
  },
  scroll: {
    flex: 1,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
  },
  saveDraftBtn: {
    height: 42,
    borderRadius: 14,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
    backgroundColor: "rgba(13, 92, 145, 0.72)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
  },
  saveDraftBtnText: {
    fontSize: 13,
    fontWeight: "700" as const,
    color: "#ffffff",
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 32,
  },
  titleSection: {
    paddingTop: 8,
    marginBottom: 16,
  },
  title: {
    fontSize: 20,
    fontWeight: "700" as const,
    color: Colors.textPrimary,
  },
  titleSub: {
    fontSize: 13,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  panel: {
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
    shadowColor: "#111827",
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 0,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700" as const,
    color: Colors.textPrimary,
    marginBottom: 10,
  },
  typeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  typeButton: {
    width: "48%",
    minHeight: 72,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.72)",
    backgroundColor: "rgba(255, 255, 255, 0.34)",
    padding: 12,
    justifyContent: "space-between",
  },
  typeButtonActive: {
    borderColor: "rgba(13, 92, 145, 0.36)",
    backgroundColor: "rgba(232, 241, 248, 0.72)",
  },
  typeIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.surface,
    marginBottom: 8,
  },
  typeLabel: {
    fontSize: 13,
    fontWeight: "700" as const,
    color: Colors.textPrimary,
  },
  label: {
    fontSize: 13,
    fontWeight: "600" as const,
    color: Colors.textPrimary,
    marginBottom: 8,
  },
  inputWrap: {
    backgroundColor: "rgba(255, 255, 255, 0.48)",
    borderRadius: 12,
    paddingHorizontal: 14,
    minHeight: 50,
    justifyContent: "center",
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.72)",
  },
  input: {
    fontSize: 14,
    color: Colors.textPrimary,
  },
  amountInput: {
    fontSize: 24,
    fontWeight: "700" as const,
    color: Colors.textPrimary,
    paddingVertical: 10,
  },
  textAreaWrap: {
    minHeight: 92,
    paddingVertical: 12,
    justifyContent: "flex-start",
  },
  textArea: {
    textAlignVertical: "top",
    minHeight: 68,
  },
  photoButton: {
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "rgba(255, 255, 255, 0.78)",
    backgroundColor: "rgba(255, 255, 255, 0.42)",
    borderRadius: 12,
    minHeight: 142,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    marginBottom: 14,
  },
  photoPreview: {
    width: "100%",
    height: 180,
  },
  photoPlaceholderIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: Colors.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  photoTitle: {
    fontSize: 14,
    fontWeight: "700" as const,
    color: Colors.textPrimary,
  },
  photoSub: {
    fontSize: 12,
    color: Colors.textTertiary,
    marginTop: 2,
  },
  submitButton: {
    height: 52,
    borderRadius: 14,
    backgroundColor: "rgba(13, 92, 145, 0.72)",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    shadowColor: "#111827",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 0,
  },
  submitButtonDisabled: {
    opacity: 0.55,
  },
  submitButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700" as const,
  },
  helperRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginTop: 12,
  },
  helperText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 17,
    color: Colors.textSecondary,
  },
  historyHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  historyCount: {
    fontSize: 12,
    color: Colors.textTertiary,
    fontWeight: "600" as const,
  },
  historyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    shadowColor: "#111827",
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 0,
  },
  historyIcon: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.primaryLight,
  },
  historyInfo: {
    flex: 1,
  },
  historyTitle: {
    fontSize: 14,
    fontWeight: "700" as const,
    color: Colors.textPrimary,
  },
  historyMeta: {
    fontSize: 12,
    color: Colors.textTertiary,
    marginTop: 2,
  },
  statusPills: {
    flexDirection: "row",
    gap: 6,
    marginTop: 8,
    flexWrap: "wrap",
  },
  statusPill: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  statusText: {
    fontSize: 10,
    fontWeight: "700" as const,
    textTransform: "capitalize",
  },
  amountText: {
    fontSize: 14,
    fontWeight: "700" as const,
    color: Colors.secondary,
  },
  loadMoreButton: {
    height: 46,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.42)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    marginTop: 6,
    marginBottom: 10,
    shadowColor: "#111827",
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 0,
  },
  loadMoreButtonDisabled: {
    opacity: 0.58,
  },
  loadMoreText: {
    fontSize: 14,
    fontWeight: "700" as const,
    color: Colors.primary,
  },
  emptyPanel: {
    alignItems: "center",
    paddingVertical: 22,
  },
  emptyText: {
    fontSize: 13,
    color: Colors.textTertiary,
    fontWeight: "600" as const,
  },
});
