import { StyleSheet } from "react-native-unistyles";
import { Colors } from "@/shared/constants/color";

export const donatedItemsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
  },
  listContent: {
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    marginBottom: 16,
  },
  backButtonFloating: {
    position: "absolute",
    top: 16,
    left: 20,
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    zIndex: 10,
  },
  titleSection: {
    marginBottom: 16,
  },
  title: {
    fontSize: 21,
    fontWeight: "700" as const,
    color: Colors.textPrimary,
  },
  subtitle: {
    marginTop: 4,
    fontSize: 13,
    color: Colors.textSecondary,
    lineHeight: 19,
  },
  itemCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    marginBottom: 10,
    shadowColor: "#111827",
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 0,
  },
  thumbnail: {
    width: 62,
    height: 62,
    borderRadius: 12,
    backgroundColor: Colors.inputBg,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.78)",
  },
  thumbnailPlaceholder: {
    alignItems: "center",
    justifyContent: "center",
  },
  itemInfo: {
    flex: 1,
  },
  itemTitle: {
    fontSize: 14,
    fontWeight: "700" as const,
    color: Colors.textPrimary,
  },
  itemMeta: {
    marginTop: 3,
    fontSize: 12,
    color: Colors.textTertiary,
  },
  donorText: {
    marginTop: 5,
    fontSize: 12,
    color: Colors.textSecondary,
    fontWeight: "600" as const,
  },
  stateContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    backgroundColor: "transparent",
  },
  stateCard: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    padding: 22,
  },
  stateText: {
    fontSize: 13,
    color: Colors.textSecondary,
    textAlign: "center",
    lineHeight: 19,
  },
  emptyCard: {
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    paddingHorizontal: 18,
    paddingVertical: 28,
    alignItems: "center",
  },
  imageCard: {
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    borderRadius: 16,
    padding: 8,
    shadowColor: "#111827",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
  },
  image: {
    width: "100%",
    aspectRatio: 4 / 3,
    borderRadius: 12,
    backgroundColor: Colors.inputBg,
  },
  imagePlaceholder: {
    width: "100%",
    aspectRatio: 4 / 3,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.42)",
  },
  detailCard: {
    marginTop: 16,
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    gap: 12,
    shadowColor: "#111827",
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 0,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  detailLabel: {
    width: 86,
    fontSize: 13,
    color: Colors.textTertiary,
  },
  detailValue: {
    flex: 1,
    fontSize: 13,
    color: Colors.textPrimary,
    fontWeight: "600" as const,
  },
  statusPill: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: Colors.secondaryLight,
  },
  statusText: {
    fontSize: 12,
    color: Colors.secondary,
    fontWeight: "700" as const,
    textTransform: "capitalize",
  },
  filterRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: "rgba(255, 255, 255, 0.34)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.72)",
  },
  filterChipLabel: {
    fontSize: 12,
    fontWeight: "700" as const,
    color: Colors.textSecondary,
  },
  ownerToggleRow: {
    flexDirection: "row",
    gap: 8,
    paddingBottom: 10,
  },
  ownerToggleChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: "rgba(255, 255, 255, 0.34)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.72)",
    flex: 1,
    justifyContent: "center",
  },
  ownerToggleChipActive: {
    backgroundColor: Colors.primaryLight,
    borderColor: Colors.primaryLight,
  },
  ownerToggleLabel: {
    fontSize: 12,
    fontWeight: "700" as const,
    color: Colors.textTertiary,
  },
  ownerToggleLabelActive: {
    color: Colors.primary,
  },
  donateButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 16,
    backgroundColor: Colors.secondary,
    borderRadius: 14,
    paddingVertical: 14,
    shadowColor: Colors.secondary,
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 14,
  },
  donateButtonText: {
    fontSize: 15,
    fontWeight: "700" as const,
    color: "#ffffff",
  },
  donatedBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 16,
    backgroundColor: Colors.secondaryLight,
    borderRadius: 14,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: Colors.secondary,
  },
  donatedBadgeText: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: Colors.secondary,
  },
});
