import { StyleSheet } from "react-native-unistyles";
import { Colors } from "@/shared/constants/color";
import { MAX_CHART_HEIGHT } from "../constants/chart";

export const donationsStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.transparent },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 20 },
  content: { flex: 1, paddingHorizontal: 20 },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  searchWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.35)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.8)",
    paddingHorizontal: 14,
    height: 44,
  },
  searchInput: { flex: 1, fontSize: 13, color: Colors.textPrimary },
  glassyBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.35)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.8)",
    alignItems: "center",
    justifyContent: "center",
  },
  batchBtn: {
    height: 44,
    borderRadius: 14,
    paddingHorizontal: 14,
    backgroundColor: "#16a34a",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  batchBtnText: { fontSize: 13, fontWeight: "700", color: "#fff" },
  addBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: Colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingView: { flex: 1, alignItems: "center", justifyContent: "center" },
  emptyCard: {
    backgroundColor: "rgba(255,255,255,0.38)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.82)",
    padding: 28,
    alignItems: "center",
  },
  emptyText: { fontSize: 13, color: Colors.textSecondary },
  filterScroll: { marginBottom: 8 },
  filterChip: {
    flexShrink: 0,
    height: 36,
    borderRadius: 999,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.34)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.72)",
  },
  filterChipActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  filterChipText: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.textSecondary,
  },
  filterChipTextActive: { color: "#fff" },
  listPadding: { paddingBottom: 50 },
  card: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(255,255,255,0.38)",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.82)",
    marginBottom: 10,
  },
  cardSelected: {
    backgroundColor: "rgba(22,163,74,0.15)",
    borderColor: "#16a34a",
  },
  draftCard: {
    borderColor: "rgba(255,200,50,0.5)",
  },
  itemImage: {
    width: 62,
    height: 62,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.inputBg,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.78)",
  },
  itemImageMoney: { backgroundColor: Colors.secondaryLight },
  itemImageFilled: { width: 62, height: 62, borderRadius: 12 },
  itemInfo: { flex: 1 },
  itemTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.textPrimary,
  },
  itemSub: {
    marginTop: 3,
    fontSize: 12,
    color: Colors.textTertiary,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: Colors.textTertiary,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxChecked: {
    borderColor: "#16a34a",
    backgroundColor: "#16a34a",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 32,
  },
  modalContent: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 8,
  },
  modalText: {
    fontSize: 14,
    color: "#666",
    lineHeight: 20,
    marginBottom: 24,
  },
  modalBtnRow: { flexDirection: "row", gap: 12 },
  modalBtn: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  modalBtnCancel: { backgroundColor: "#f0f0f0" },
  modalBtnConfirm: { backgroundColor: "#16a34a" },
  modalBtnText: { fontSize: 14, fontWeight: "600" },
  modalBtnTextCancel: { color: "#666" },
  modalBtnTextConfirm: { color: "#fff" },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.3)",
  },

  // original styles retained below
  titleSection: {
    paddingTop: 8,
    marginBottom: 16,
  },
  title: {
    fontSize: 20,
    fontWeight: "700" as const,
    color: Colors.textPrimary,
  },
  titleSub: {
    fontSize: 13,
    color: Colors.textTertiary,
    marginTop: 1,
  },
  summaryRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 16,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 14,
  },
  summaryIcon: {
    width: 30,
    height: 30,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  summaryLabel: {
    fontSize: 12,
    color: Colors.textTertiary,
    marginBottom: 3,
  },
  summaryValue: {
    fontSize: 17,
    fontWeight: "700" as const,
    letterSpacing: -0.3,
  },
  chartCard: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 16,
    marginBottom: 22,
  },
  chartHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  chartTitle: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: Colors.textPrimary,
  },
  legendRow: {
    flexDirection: "row",
    gap: 12,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 2,
  },
  legendText: {
    fontSize: 11,
    color: Colors.textTertiary,
  },
  chart: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    height: MAX_CHART_HEIGHT + 24,
  },
  barGroup: {
    flex: 1,
    alignItems: "center",
  },
  bars: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 3,
    marginBottom: 6,
  },
  bar: {
    width: 12,
    borderRadius: 3,
    minHeight: 4,
  },
  barReceived: {
    backgroundColor: Colors.secondary,
  },
  barSpent: {
    backgroundColor: Colors.accent,
    opacity: 0.7,
  },
  barLabel: {
    fontSize: 10,
    color: Colors.textTertiary,
    fontWeight: "500" as const,
  },
  transactionsTitle: {
    fontSize: 15,
    fontWeight: "600" as const,
    color: Colors.textPrimary,
    marginBottom: 10,
  },
  transRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: 13,
    marginBottom: 6,
  },
  transIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  transInfo: { flex: 1 },
  transDonor: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: Colors.textPrimary,
  },
  transMeta: {
    fontSize: 12,
    color: Colors.textTertiary,
    marginTop: 2,
  },
  transAmount: {
    fontSize: 14,
    fontWeight: "600" as const,
  },
});
