import { StyleSheet } from "react-native-unistyles";
import { Colors } from "@/shared/constants/color";

export const verifyItemsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    marginBottom: 16,
  },
  backButtonFloating: {
    position: "absolute",
    top: 16,
    left: 20,
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    zIndex: 10,
  },
  titleSection: {
    marginBottom: 16,
  },
  title: {
    fontSize: 21,
    fontWeight: "700" as const,
    color: Colors.textPrimary,
  },
  subtitle: {
    marginTop: 4,
    fontSize: 13,
    color: Colors.textSecondary,
    lineHeight: 19,
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    marginBottom: 10,
    shadowColor: "#111827",
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 0,
  },
  thumbnail: {
    width: 58,
    height: 58,
    borderRadius: 12,
    backgroundColor: Colors.inputBg,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.78)",
  },
  itemInfo: {
    flex: 1,
  },
  itemTitle: {
    fontSize: 14,
    fontWeight: "700" as const,
    color: Colors.textPrimary,
  },
  itemMeta: {
    marginTop: 3,
    fontSize: 12,
    color: Colors.textTertiary,
  },
  donorText: {
    marginTop: 5,
    fontSize: 12,
    color: Colors.textSecondary,
    fontWeight: "600" as const,
  },
  stateContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    backgroundColor: "transparent",
  },
  stateCard: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    padding: 22,
  },
  stateText: {
    fontSize: 13,
    color: Colors.textSecondary,
    textAlign: "center",
    lineHeight: 19,
  },
  emptyCard: {
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    paddingHorizontal: 18,
    paddingVertical: 28,
    alignItems: "center",
  },
  imageCard: {
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    borderRadius: 16,
    padding: 8,
    shadowColor: "#111827",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 0,
  },
  image: {
    width: "100%",
    aspectRatio: 4 / 3,
    borderRadius: 12,
    backgroundColor: Colors.inputBg,
  },
  detailCard: {
    marginTop: 16,
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    gap: 12,
    shadowColor: "#111827",
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 0,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  detailLabel: {
    width: 86,
    fontSize: 13,
    color: Colors.textTertiary,
  },
  detailValue: {
    flex: 1,
    fontSize: 13,
    color: Colors.textPrimary,
    fontWeight: "600" as const,
  },
  statusPill: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: Colors.primaryLight,
  },
  statusText: {
    fontSize: 12,
    color: Colors.primary,
    fontWeight: "700" as const,
    textTransform: "capitalize",
  },
  actionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
  },
  actionButton: {
    flex: 1,
    height: 52,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    shadowColor: "#111827",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 0,
  },
  verifyButton: {
    backgroundColor: "rgba(29, 158, 84, 1)",
    borderWidth:1,
    borderColor: "rgba(29, 158, 84, 0.96)",
  },
  rejectButton: {
    backgroundColor: "rgba(220, 38, 38, 1)",
    borderWidth:1,
    borderColor: "rgba(220, 38, 38, 0.96)",
  },
  actionButtonDisabled: {
    opacity: 0.55,
  },
  actionText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700" as const,
  },
});
