import { StyleSheet } from "react-native-unistyles";
import { Colors } from "@/shared/constants/color";
import { Dimensions } from "react-native";

export const activityDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 32,
  },
  title: {
    fontSize: 22,
    fontWeight: "700" as const,
    color: Colors.textPrimary,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    zIndex: 20,
  },
  titleWrap: {
    flex: 1,
  },
  titleActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  subtitle: {
    marginTop: 6,
    fontSize: 14,
    color: Colors.textSecondary,
    lineHeight: 20,
  },
  metaCard: {
    marginTop: 18,
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    gap: 12,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  metaLabel: {
    fontSize: 13,
    color: Colors.textTertiary,
    width: 80,
  },
  metaValue: {
    flex: 1,
    fontSize: 13,
    color: Colors.textPrimary,
  },
  statusRow: {
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statusLabel: {
    fontSize: 13,
    color: Colors.textTertiary,
  },
  statusPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: Colors.primaryLight,
  },
  statusText: {
    fontSize: 12,
    fontWeight: "600" as const,
    color: Colors.primary,
  },
  deleteIconButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: Colors.errorLight,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#FECACA",
  },
  deleteIconButtonDisabled: {
    opacity: 0.6,
  },
  statusMenuWrap: {
    position: "relative",
  },
  statusMenuTrigger: {
    minWidth: 44,
    height: 42,
    borderRadius: 12,
    backgroundColor: Colors.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#BFDBFE",
    paddingHorizontal: 12,
  },
  statusMenuTriggerDisabled: {
    opacity: 0.6,
  },
  statusMenuDropdown: {
    position: "absolute",
    top: 50,
    right: 0,
    width: 164,
    borderRadius: 14,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    padding: 8,
    gap: 4,
    shadowColor: "#111827",
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 18,
    elevation: 8,
  },
  statusMenuOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    minHeight: 40,
    borderRadius: 10,
    paddingHorizontal: 10,
  },
  statusMenuOptionActive: {
    backgroundColor: Colors.primaryLight,
  },
  statusMenuOptionText: {
    fontSize: 13,
    color: Colors.textPrimary,
    fontWeight: "600" as const,
  },
  statusMenuOptionTextActive: {
    color: Colors.primary,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.82)",
    marginBottom: 16,
  },
  backButtonText: {
    fontSize: 14,
    color: Colors.primary,
    fontWeight: "600" as const,
  },
  backButtonIcon: {
    marginTop: 2,
  },
  stateContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  stateText: {
    marginTop: 12,
    fontSize: 13,
    color: Colors.textTertiary,
    textAlign: "center",
  },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width:Dimensions.get("window").width,
    height:Dimensions.get("window").height,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 999,
  },
});
